name: Deploy to Firebase

on:
  push:
    branches:
      - main  # 触发条件：当推送到 main 分支时

jobs:
  deploy:
    runs-on: ubuntu-latest  # 运行环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码

      - name: Install Firebase CLI
        run: npm install -g firebase-tools  # 安装 Firebase CLI

      - name: Deploy to Firebase Hosting
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}  # 部署到 Firebase
